# Generated by Django 4.0.6 on 2022-07-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matric_no',
            field=models.CharField(default='2022/26/138AC', max_length=50, unique=True),
        ),
    ]
