# Generated by Django 4.0.6 on 2022-07-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_matric_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matric_no',
            field=models.CharField(default='2022/03/930AB', max_length=50, unique=True),
        ),
    ]
