# Generated by Django 4.0.6 on 2022-07-23 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('course_code', models.CharField(blank=True, max_length=250, null=True)),
                ('credit_unit', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='LevelAndSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100level'), (200, '200level'), (300, '300level'), (400, '400level'), (500, '500level')])),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'first semester'), (2, 'second semester')])),
            ],
            options={
                'verbose_name': 'Level And Semester',
                'verbose_name_plural': 'Level And Semesters',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('points', models.PositiveIntegerField(default=0, editable=False)),
                ('unit_points', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'results',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('result', models.ManyToManyField(to='student.result')),
            ],
            options={
                'verbose_name': 'Student Course',
                'verbose_name_plural': 'Student Courses',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='leave_and_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.levelandsemester'),
        ),
        migrations.AddField(
            model_name='course',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='CGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credit_units', models.IntegerField(blank=True, default=0, null=True)),
                ('total_unit_points', models.IntegerField(blank=True, default=0, null=True)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('student_course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentcourse')),
            ],
            options={
                'verbose_name': 'CGPA',
                'verbose_name_plural': 'CGPAs',
            },
        ),
    ]
