# Generated by Django 4.0.6 on 2022-07-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_studentcourse_result_studentcourse_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgpa',
            name='student_course',
        ),
        migrations.AddField(
            model_name='cgpa',
            name='student_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentcourse'),
        ),
    ]
