# Generated by Django 4.0.6 on 2022-07-18 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_matric_no'),
        ('student', '0005_remove_cgpa_student_course_cgpa_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
