# Generated by Django 4.0.6 on 2022-07-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_course_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cgpa',
            options={'verbose_name': 'CGPA', 'verbose_name_plural': 'CGPAs'},
        ),
        migrations.AlterField(
            model_name='cgpa',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='cgpa',
            table=None,
        ),
    ]
