# Generated by Django 4.0.6 on 2022-07-21 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_matric_no'),
        ('student', '0007_alter_cgpa_options_alter_cgpa_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgpa',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
