# Generated by Django 4.0.6 on 2022-07-21 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0008_cgpa_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgpa',
            name='profile',
        ),
        migrations.AddField(
            model_name='cgpa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
