# Generated by Django 4.0.6 on 2022-07-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_cgpa_cgpa_alter_cgpa_total_credit_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgpa',
            name='student_course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentcourse'),
        ),
    ]
